// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQLB4viRJI75hDf3XNmDPTzHR1C9yntk',
    appId: '1:640955835827:web:143b3269b0143797d257c6',
    messagingSenderId: '640955835827',
    projectId: 'flutter-challenge-6a5bc',
    authDomain: 'flutter-challenge-6a5bc.firebaseapp.com',
    storageBucket: 'flutter-challenge-6a5bc.appspot.com',
    measurementId: 'G-BWFT61QLH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpdHmGTh-uikcgj6Kn9YTxbS_uPyKLwiU',
    appId: '1:640955835827:android:e76025ec0d36f82dd257c6',
    messagingSenderId: '640955835827',
    projectId: 'flutter-challenge-6a5bc',
    storageBucket: 'flutter-challenge-6a5bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ1iVZ2QdKwMYh_gUlFPz1xInp1fJsGA0',
    appId: '1:640955835827:ios:9931dde69127a3bdd257c6',
    messagingSenderId: '640955835827',
    projectId: 'flutter-challenge-6a5bc',
    storageBucket: 'flutter-challenge-6a5bc.appspot.com',
    iosClientId: '640955835827-5ob02ko9ol7c7olr3241h1kc77tgmqi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ1iVZ2QdKwMYh_gUlFPz1xInp1fJsGA0',
    appId: '1:640955835827:ios:9931dde69127a3bdd257c6',
    messagingSenderId: '640955835827',
    projectId: 'flutter-challenge-6a5bc',
    storageBucket: 'flutter-challenge-6a5bc.appspot.com',
    iosClientId: '640955835827-5ob02ko9ol7c7olr3241h1kc77tgmqi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
